export const datos = [
  {
    lote: "LOTE 11A/LOTE 17",
    atlas: "MTAT.F01",
    nombre: "MURTATZA",
    miga: "4811004",
    provincia: "Vizcaya",
    coordenadas: "",
    tipo_edificio: "ARMARIO",
    tipo_repliegue: "Completo",
    senda:  "ACELERADA_2026",
    fecha_abandono: "",
    prioritario: false,
  },
  {
    lote: "LOTE 17 (Abierta por: user)",
    atlas: "AMET.",
    nombre: "AMETLLA VALLES",
    miga: "0865007",
    provincia: "Barcelona",
    coordenadas: "41.66778, 2.26388",
    tipo_edificio: "Central M",
    tipo_repliegue: "Completo",
    senda:  "ACELERADA_2026",
    fecha_abandono: "",
    prioritario: false,
  },
  {
    lote: "LOTE 17",
    atlas: "AMPU.",
    nombre: "AMPUERO",
    miga: "3963002",
    provincia: "Cantabria",
    coordenadas: "43.34265, -3.41759",
    tipo_edificio: "Central M",
    tipo_repliegue: "Completo",
    senda:  "ACELERADA_2026",
    fecha_abandono: "",
    prioritario: false,
  },
  {
    lote: "LOTE 17",
    atlas: "ARBC.",
    nombre: "ARBUCIES",
    miga: "1771001",
    provincia: "Girona",
    coordenadas: "41.81490, 2.51237",
    tipo_edificio: "Central S",
    tipo_repliegue: "Completo",
    senda:  "ACELERADA_2026",
    fecha_abandono: "",
    prioritario: false,
  },
  {
    lote: "LOTE 17",
    atlas: "CERS.",
    nombre: "CERCS",
    miga: "0861014",
    provincia: "Barcelona",
    coordenadas: "42.15192, 1.85692",
    tipo_edificio: "Central M",
    tipo_repliegue: "Completo",
    senda:  "ACELERADA_2026",
    fecha_abandono: "",
    prioritario: false,
  },
  {
    lote: "LOTE 17",
    atlas: "CNIT.CT",
    nombre: "CUNIT VERDAGER",
    miga: "4368003",
    provincia: "Tarragona",
    coordenadas: "41.19741, 1.63643",
    tipo_edificio: "Central S",
    tipo_repliegue: "Completo",
    senda:  "ACELERADA_2026",
    fecha_abandono: "",
    prioritario: false,
  },
  {
    lote: "LOTE 17",
    atlas: "CVRM.",
    nombre: "CERVERA MONTES",
    miga: "4567009",
    provincia: "Toledo",
    coordenadas: "40.0517, -4.80958",
    tipo_edificio: "Central S",
    tipo_repliegue: "Completo",
    senda:  "ACELERADA_2026",
    fecha_abandono: "",
    prioritario: false,
  },
  {
    lote: "LOTE 17",
    atlas: "DMUS.",
    nombre: "DAIMUS",
    miga: "4667007",
    provincia: "Valencia",
    coordenadas: "38.96856, -0.15086",
    tipo_edificio: "Central S",
    tipo_repliegue: "Completo",
    senda:  "ACELERADA_2026",
    fecha_abandono: "",
    prioritario: false,
  },
  {
    lote: "LOTE 17",
    atlas: "FNCB.",
    nombre: "FERNANCABALL",
    miga: "1365003",
    provincia: "Ciudad Real",
    coordenadas: "39.12648, -3.90047",
    tipo_edificio: "Central XS",
    tipo_repliegue: "Completo",
    senda:  "ACELERADA_2026",
    fecha_abandono: "12/04/2026",
    prioritario: false,
  },
  {
    lote: "LOTE 17",
    atlas: "L.MI",
    nombre: "L-MISSIONS",
    miga: "2510004",
    provincia: "Lleida",
    coordenadas: "41.61343, 0.61532",
    tipo_edificio: "Central XL",
    tipo_repliegue: "Completo",
    senda:  "ACELERADA_2026",
    fecha_abandono: "",
    prioritario: false,
  },
  {
    lote: "LOTE 17",
    atlas: "LLIN.",
    nombre: "LLINARS VALLES",
    miga: "0865010",
    provincia: "Barcelona",
    coordenadas: "41.63859, 2.39553",
    tipo_edificio: "Central M",
    tipo_repliegue: "Completo",
    senda:  "ACELERADA_2026",
    fecha_abandono: "",
    prioritario: false,
  },
  {
    lote: "LOTE 17",
    atlas: "LLVA.",
    nombre: "LLIÇA VALL",
    miga: "0865012",
    provincia: "Barcelona",
    coordenadas: "41.59261, 2.24291",
    tipo_edificio: "Central M",
    tipo_repliegue: "Completo",
    senda:  "ACELERADA_2026",
    fecha_abandono: "",
    prioritario: false,
  },
  {
    lote: "LOTE 18",
    atlas: "B.HO",
    nombre: "BARCELONA HORTA",
    miga: "0810013",
    provincia: "Barcelona",
    coordenadas: "41.428214, 2.163402",
    tipo_edificio: "Central XL",
    tipo_repliegue: "Completo C.V.",
    senda:  "ACELERADA_2026",
    fecha_abandono: "",
    prioritario: false,
  },
  {
    lote: "LOTE 18",
    atlas: "M.EN",
    nombre: "MADRID ENTREVIAS",
    miga: "2810056",
    provincia: "Madrid",
    coordenadas: "40.376957, -3.662244",
    tipo_edificio: "Central XL",
    tipo_repliegue: "Completo C.V.",
    senda:  "ACELERADA_2026",
    fecha_abandono: "",
    prioritario: false,
  },
  {
    lote: "LOTE 18 (Abierta por: Francisco Javier Chacón Rivero)",
    atlas: "M.IT",
    nombre: "MADRID INTERNACIONAL",
    miga: "2850006",
    provincia: "Madrid",
    coordenadas: "40.53890, -3.64202",
    tipo_edificio: "Central XL",
    tipo_repliegue: "Parcial C.V",
    senda:  "ACELERADA_2026",
    fecha_abandono: "",
    prioritario: false,
  }
];